# Commiting template file Changes
# 1
# 10/04/2026
AWSTemplateFormatVersion: '2010-09-09'
Description: VPC-sarhen0207 in us-west-2 spanning 3 AZs

Parameters:
  EnvironmentName:
    Type: String
    Default: VPC-sarhen0207

Mappings:
  RegionMap:
    us-west-2:
      AZ1: us-west-2a
      AZ2: us-west-2b
      AZ3: us-west-2c

Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: !Ref EnvironmentName

  SubnetAZ1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.0.1.0/24
      AvailabilityZone: !FindInMap [RegionMap, "us-west-2", "AZ1"]
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Sub "${EnvironmentName}-subnet-az1"

  SubnetAZ2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.0.2.0/24
      AvailabilityZone: !FindInMap [RegionMap, "us-west-2", "AZ2"]
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Sub "${EnvironmentName}-subnet-az2"

  SubnetAZ3:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.0.3.0/24
      AvailabilityZone: !FindInMap [RegionMap, "us-west-2", "AZ3"]
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Sub "${EnvironmentName}-subnet-az3"

Outputs:
  VPCId:
    Value: !Ref VPC
    Description: VPC ID

  Subnet1Id:
    Value: !Ref SubnetAZ1

  Subnet2Id:
    Value: !Ref SubnetAZ2

  Subnet3Id:
    Value: !Ref SubnetAZ3

